name: Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v5
      with:
        go-version: 1.19.x

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make release
